### ISSUE TITLE
Stress field with is_outputting_averaged_fields=off

### ISSUE THREAD

**Issue by rclam** [tan2/DynEarthSol-old#7]
My name is Ryann Lam. I am a PhD student working with Eunseo at CERI. I'm reporting an issue that I ran into as I am learning about DES.

I used a fresh clone of the code and examples/core-complex.cfg. The example runs well but the vtu files created with 2vtk.py seem to contain corrupted stress I and II (screenshot 1). However, these fields look fine when the option, is_outputting_averaged_fields , is turned on (screenshot 2).

<img width="1264" alt="Screen Shot 2021-04-02 at 5 18 08 PM" src="https://user-images.githubusercontent.com/75513951/113619290-6acdf580-961e-11eb-9921-de71d5946b0e.png">
<img width="1264" alt="Screen Shot 2021-04-05 at 2 32 09 PM" src="https://user-images.githubusercontent.com/75513951/113619306-6e617c80-961e-11eb-95de-896ca6176aab.png">

**Comment by tan2** [comment]
Thanks for the report. I will investigate it.

**Comment by tan2** [comment]
It is fixed in https://github.com/tan2/DynEarthSol-old/commit/4844da3ced8e7b4e7b7c960dae7a7bf8d7556c16.
